"""Add title and description to Reminder

Revision ID: fb0e148144cc
Revises: fb330eb04834
Create Date: 2024-06-11 17:49:03.462240

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb0e148144cc'
down_revision = 'fb330eb04834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=True))
        batch_op.alter_column('date',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reminder', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('time')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
